version: '2'
services:
  cadvisor:
    labels:
      io.rancher.scheduler.global: 'true'
    tty: true
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
      - "/:/rootfs:ro"  
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk:/dev/disk:ro"
    ports:
       - ${CADVISOR_PORT}:8080

  node-exporter:
    # This exporter will inform about of cpu in each host configured in Rancher becasuse
    # the scheduler global configuration
    labels:
      io.rancher.scheduler.global: 'true'
    tty: true
    image: prom/node-exporter:latest
    stdin_open: true
    ports:
        - ${NODEEX_PORT}:9100