.catalog:
  name: "Prometheus"
  version: "1.0.0"
  description: "Prometheus Monitoring Solution"
  uuid: prometheus-demo
  minimum_rancher_version: v1.6.11
  questions:
  - variable: "CATTLE_URL"
    label: "Rancher API v2 URL"
    description: "i.e. https://rancher.example.com:9090/v2-beta"
    default: ""
    required: true
    type: "string"
  - variable: "REGISTRY"
    label: "REGISTRY to lockup the image"
    description: "Should be accesible from Rancher"
    default: "registry-dev.example.com/"
    required: true
    type: "string"
  - variable: "RANCHER_SERVER"
    label: "Rancher Server"
    description: "IP Address of the rancher server, no HTTP or slashes. This is only required for users that have enabled metrics to be exported by Rancher"
    default: "0.0.0.0"
    required: false
    type: "string"
  - variable: "RANCHER_SECRET_KEY"
    label: "Rancher SecretKey"
    description: "This key can be generated in the API section"
    default: ""
    required: true
    type: "string"
  - variable: "RANCHER_ACCESS_KEY"
    label: "Rancher Access Key"
    description: "This key can be generated in the API section"
    default: ""
    required: true
    type: "string"
  - variable: "PROM_CONFIG"
    label: "Prometheus config PATH"
    description: "path where could be located the prometheus.yml"
    default: "/etc/prom-conf/prometheus.yml"
    required: true
    type: "string"
  - variable: "PROM_ARGS"
    label: "Execute Arguments"
    description: "Aditional Arguments to execute Prometheus (Config path is already in the command)"
    default: "--storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles"
    required: false
  - variable: "VOLUME_DRIVER"
    description: "The VOLUME driver to associate with this server"
    label: "VOLUME Driver"
    required: true
    default: "local"
    type: enum
    options:
      - local

prometheus:
  scale: 1
  health_check:
    port: 9090
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

grafana:
  scale: 1
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

prometheus-rancher-exporter:
  scale: 1
  health_check:
    port: 9173
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
